---
title: "Data Cleaning Process - Springboard Capstone"
author: "DeAnna Dailey"
date: "3/14/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



##1) Remove rows with no email address from the customer export
Any row without an email address is some kind of error, since the whole system runs on email addresses

##2) Join two tables together, matching emails, and keeping all data from both tables
Data came from two sources that I want in one table.

##3) Add a unique ID to each row so data can be matched back to actual users for real client
I want to anonymize data for this project, but still be able to sync back to real user emails for use by the real client.

##4) Remove identifying info - name, phone, street address, email, etc.
Anonymize data.

##5) Remove unneeded columns the show data not relevant to this project (like quiz results)
Lots of extraneous data that isn't relevant to this project, or is accurately captured by the contact tags column, so doesn't need to be repeated.

##6) Clean up column names
Convert all column names to lowercase with no spaces

##7) Combine all duplicate address columns, with priority for Shipping address data
The two tables I combined both had address data. The data from shipping address is more accurate, but when that address is missing, it uses the other field if there's data there.

##8) Turn Contact Tags into a searchable list
May still do something else with this column in the future - maybe split into One Hot 

##9) Create Total Spent/per time period to resolve the different lifespans of each customer
-turn date fields from chr to dates

-convert spent_to_date to numeric, by removing dollar sign from beginning and converting

-create total_spent column from whichever is larger of total_spent_sh or spent_to_date

-create lifespan of customer by subtracting date_added from last_activity

-convert lifespan to days from seconds (minimum lifespan of 1 day - even if they only signed up for an hour, we're still going to say they were 1 day)

-create new column avg_daily_spend_lifespan by dividing total_spent by lifespan


